# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "logger": "00_validation.ipynb",
    "GridGenerator": "00_grids.ipynb",
    "Validator": "00_validation.ipynb",
    "Validator.validate": "00_validation.ipynb",
    "OrientationValidator": "00_validation.ipynb",
    "OrientationValidator.check": "00_validation.ipynb",
    "OrientationValidator.fix": "00_validation.ipynb",
    "GeometryValidation": "00_validation.ipynb",
    "GeometryValidation.validate_all": "00_validation.ipynb",
    "ValidationError": "00_validation.ipynb",
}

modules = ["grids.py", "validation.py"]

doc_url = "https://thinkingmachines.github.io/geowrangler/"

git_url = "https://github.com/thinkingmachines/geowrangler/tree/master/"


def custom_doc_links(name):
    return None
