# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GridGenerator": "00_grids.ipynb", "logger": "00_grids.ipynb"}

modules = ["grids.py"]

doc_url = "https://thinkingmachines.github.io/geowrangler/"

git_url = "https://github.com/thinkingmachines/geowrangler/tree/master/"


def custom_doc_links(name):
    return None
