# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "logger": "00_validation.ipynb",
    "SquareGridBoundary": "00_grids.ipynb",
    "SquareGridGenerator": "00_grids.ipynb",
    "SquareGridGenerator.create_cell": "00_grids.ipynb",
    "SquareGridGenerator.create_grid_for_polygon": "00_grids.ipynb",
    "SquareGridGenerator.generate_grid": "00_grids.ipynb",
    "H3GridGenerator": "00_grids.ipynb",
    "H3GridGenerator.get_hexes_for_polygon": "00_grids.ipynb",
    "H3GridGenerator.generate_grid": "00_grids.ipynb",
    "BingTileGridGenerator": "00_grids.ipynb",
    "BingTileGridGenerator.generate_grid": "00_grids.ipynb",
    "ValidationError": "00_validation.ipynb",
    "BaseValidator": "00_validation.ipynb",
    "BaseValidator.validate": "00_validation.ipynb",
    "OrientationValidator": "00_validation.ipynb",
    "OrientationValidator.check": "00_validation.ipynb",
    "OrientationValidator.fix": "00_validation.ipynb",
    "CrsBoundsValidator": "00_validation.ipynb",
    "CrsBoundsValidator.get_check_arguments": "00_validation.ipynb",
    "CrsBoundsValidator.check": "00_validation.ipynb",
    "CrsBoundsValidator.fix": "00_validation.ipynb",
    "SelfIntersectingValidator": "00_validation.ipynb",
    "SelfIntersectingValidator.check": "00_validation.ipynb",
    "SelfIntersectingValidator.fix": "00_validation.ipynb",
    "NullValidator": "00_validation.ipynb",
    "NullValidator.check": "00_validation.ipynb",
    "NullValidator.fix": "00_validation.ipynb",
    "AreaValidator": "00_validation.ipynb",
    "AreaValidator.check": "00_validation.ipynb",
    "AreaValidator.fix": "00_validation.ipynb",
    "GeometryValidation": "00_validation.ipynb",
    "GeometryValidation.validate_all": "00_validation.ipynb",
    "GEO_INDEX_NAME": "02_vector_zonal_stats.ipynb",
    "create_zonal_stats": "02_vector_zonal_stats.ipynb",
    "tms": "02_vector_zonal_stats.ipynb",
    "get_quadkey": "02_vector_zonal_stats.ipynb",
    "compute_quadkey": "02_vector_zonal_stats.ipynb",
    "validate_aoi_quadkey": "02_vector_zonal_stats.ipynb",
    "validate_data_quadkey": "02_vector_zonal_stats.ipynb",
    "quadkey_to_tile": "02_vector_zonal_stats.ipynb",
    "create_bingtile_zonal_stats": "02_vector_zonal_stats.ipynb",
}

modules = ["grids.py", "validation.py", "vector_zonal_stats.py"]

doc_url = "https://geowrangler.web.app/"

git_url = "https://github.com/thinkingmachines/geowrangler/tree/master/"


def custom_doc_links(name):
    return None
