name: Check code coverage
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GDAL_VERSION: 3.10.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.14
      - uses: trundev/setup-gdal@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install -e ".[dev]"
      # Code cove with a min percentage
      - run: pytest --cov --cov-config=.coveragerc --cov-fail-under=80 -n auto
