name: Check code coverage
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.14
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            gdal
          version: 1.0
      - run: pip install -e ".[dev]"
      # Code cove with a min percentage
      - run: pytest --cov --cov-config=.coveragerc --cov-fail-under=80 -n auto
