name: Check code coverage
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.14
      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev
      - name: Set GDAL environment variables
        run: echo "GDAL_VERSION=$(gdal-config --version)" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run pytest with coverage with min percentage
        run: pytest --cov --cov-config=.coveragerc --cov-fail-under=80 -n auto
